In [28]:
import pandas as pd
import numpy as np
import time
import os
from collections import defaultdict

In [29]:
def read_files(filename):
    data = pd.read_csv(filename)
    return data

In [30]:
directory = "../Data/Cleaned_Data/"

In [31]:
data_nyumc = read_files(directory+"nyumc.csv")
data_nyumc.head()

,Unnamed: 0,flu,fever,sorethroat,cough,muscle,headache,fatigue,vomit,nausea,diarrhea,male,age 0-4,age 5-15,age 16-44,age 45-64,age 65+,female
0,3,0,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0
1,4,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1
2,6,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
3,8,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
4,9,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1

In [32]:
data_gv = read_files(directory+"goviral.csv")
data_gv.head()

,Unnamed: 0,virus,age,fever,cough,runnynose,sorethroat,muscle,fatigue,chills,...,nausea,diarrhea,vomit,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,0,1,33.0,0,0,0,1,1,1,1,...,0,1,0,1.0,0.0,0,0,1,0,0
1,1,1,33.0,0,0,0,1,1,1,1,...,0,1,0,1.0,0.0,0,0,1,0,0
2,2,1,30.0,1,1,1,0,1,1,1,...,0,0,0,0.0,1.0,0,0,1,0,0
3,3,1,30.0,1,1,1,0,1,1,1,...,0,0,0,0.0,1.0,0,0,1,0,0
4,4,1,33.0,0,1,1,0,1,1,1,...,0,0,0,1.0,0.0,0,0,1,0,0

In [33]:
data_fw = read_files(directory+"fluwatch.csv")
data_fw.head()

,Unnamed: 0,fever,cough,sorethroat,runnynose,blockednose,sneeze,diarrhea,muscle,headache,flu,age 0-4,age 45-64,age 16-44,age 5-15,age 65+,male,female
0,0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,4,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [34]:
data_hk = read_files(directory+"hongkong.csv")
data_hk.head()

,Unnamed: 0,headache,sorethroat,cough,muscle,runnynose,phlegm,male,flu,fever,age 5-15,age 16-44,age 0-4,age 65+,age 45-64,gender,female
0,0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
2,2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1
3,3,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1

In [35]:
data_ht = read_files(directory+"hutterite.csv")
data_ht.head()

,RID,virus,chills,cough,fatigue,fever,headache,muscle,runnynose,blockednose,sorethroat,female,male,age 45-64,age 16-44,age 5-15,age 65+,age 0-4,earache
0,1,0.0,0,0,0,0,1,0,0,0,0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0,1,0,0,1,1,1,1,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0,0,0,0,1,0,1,1,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4,0.0,0,1,0,0,0,0,1,0,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5,0.0,0,1,0,0,0,0,1,0,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [36]:
data_lb = read_files(directory+'loeb.csv')
data_lb.head()

,chills,cough,fever,headache,male,muscle,runnynose,sinus,sorethroat,age 0-4,age 5-15,age 16-44,age 45-64,age 65+,virus,female
0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1
1,0,1,0,0,1,0,1,0,1,0,1,0,0,0,1,0
2,1,0,0,1,1,1,0,1,1,0,1,0,0,0,1,0
3,0,1,1,0,1,0,1,0,1,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1

### Symptoms and target variables for the datasets

In [37]:
DATASETS = [data_nyumc,data_gv,data_fw,data_hk,data_ht]
DATASET_NAMES = ['NYUMC','GoViral','FluWatch','HongKong','Hutterite','Loeb']
symptoms = defaultdict()
target_variable = defaultdict()

In [38]:
def get_columns(dataframe):
    columns = list(dataframe.columns)
    return columns

In [39]:
def print_columns(dataset):
    print("The features in this dataset are :\n",get_columns(dataset))
    print("_________________________________________________________")

In [40]:
#for NYUMC:
print_columns(data_nyumc)
symptoms['NYUMC'] = [
                     'fever',
                     'sorethroat',
                     'cough',
                     'muscle',
                     'headache',
                     'fatigue',
                     'vomit',
                     'nausea',
                     'diarrhea']
target_variable['NYUMC'] = 'flu'

The features in this dataset are :
 ['Unnamed: 0', 'flu', 'fever', 'sorethroat', 'cough', 'muscle', 'headache', 'fatigue', 'vomit', 'nausea', 'diarrhea', 'male', 'age 0-4', 'age 5-15', 'age 16-44', 'age 45-64', 'age 65+', 'female']
_________________________________________________________

In [41]:
#for GoViral
print_columns(data_gv)
symptoms['GoViral'] = [
                       'fever',
                       'cough',
                       'runnynose',
                       'sorethroat',
                       'muscle',
                       'fatigue',
                       'chills',
                       'shortness of breath',
                       'leg pain',
                       'nausea',
                       'diarrhea',
                       'vomit']
target_variable['GoViral'] = 'virus'

The features in this dataset are :
 ['Unnamed: 0', 'virus', 'age', 'fever', 'cough', 'runnynose', 'sorethroat', 'muscle', 'fatigue', 'chills', 'shortness of breath', 'leg pain', 'nausea', 'diarrhea', 'vomit', 'male', 'female', 'age 0-4', 'age 5-15', 'age 16-44', 'age 45-64', 'age 65+']
_________________________________________________________

In [42]:
#for FluWatch
print_columns(data_fw)
symptoms['FluWatch'] = ['fever',
                        'cough',
                        'sorethroat',
                        'runnynose',
                        'blockednose',
                        'sneeze',
                        'diarrhea',
                        'muscle',
                        'headache',
                        ]
target_variable['FluWatch'] = 'flu'

The features in this dataset are :
 ['Unnamed: 0', 'fever', 'cough', 'sorethroat', 'runnynose', 'blockednose', 'sneeze', 'diarrhea', 'muscle', 'headache', 'flu', 'age 0-4', 'age 45-64', 'age 16-44', 'age 5-15', 'age 65+', 'male', 'female']
_________________________________________________________

In [43]:
#for HongKong
print_columns(data_hk)
symptoms['HongKong'] = ['headache',
                        'sorethroat',
                        'cough',
                        'muscle',
                        'runnynose',
                        'phlegm',
                        'fever']
target_variable['HongKong'] = 'flu'

The features in this dataset are :
 ['Unnamed: 0', 'headache', 'sorethroat', 'cough', 'muscle', 'runnynose', 'phlegm', 'male', 'flu', 'fever', 'age 5-15', 'age 16-44', 'age 0-4', 'age 65+', 'age 45-64', 'gender', 'female']
_________________________________________________________

In [44]:
#for hutterite
print_columns(data_ht)
symptoms['Hutterite'] = [
                         'chills',
                         'cough',
                         'fatigue',
                         'fever',
                         'headache',
                         'muscle',
                         'runnynose',
                         'blockednose',
                         'sorethroat',
                         'earache']
target_variable['Hutterite'] = 'virus'

The features in this dataset are :
 ['RID', 'virus', 'chills', 'cough', 'fatigue', 'fever', 'headache', 'muscle', 'runnynose', 'blockednose', 'sorethroat', 'female', 'male', 'age 45-64', 'age 16-44', 'age 5-15', 'age 65+', 'age 0-4', 'earache']
_________________________________________________________

In [45]:
#for loeb
print_columns(data_lb)
symptoms['Loeb'] = ['chills','cough','fever','headache','muscle','runnynose','sinus','sorethroat']
target_variable['Loeb'] = 'virus'

The features in this dataset are :
 ['chills', 'cough', 'fever', 'headache', 'male', 'muscle', 'runnynose', 'sinus', 'sorethroat', 'age 0-4', 'age 5-15', 'age 16-44', 'age 45-64', 'age 65+', 'virus', 'female']
_________________________________________________________

### Determine the feature space

In [46]:
common_features = []
all_features = []

In [47]:
def get_common_features():
    common_features = list(set(symptoms['NYUMC']) & set(symptoms['GoViral']) & set(symptoms['FluWatch']) & set(symptoms['HongKong']) & set(symptoms['Hutterite']) &set(symptoms['Loeb']))
    return common_features

In [48]:
common_features = get_common_features()
print("The common features in all the datasets are :\n")
for i in common_features:
    print(i)
print("Number of common features are :",len(common_features))
print("____________________________________")

The common features in all the datasets are :

fever
cough
muscle
sorethroat
Number of common features are : 4
____________________________________

There are four symptoms [fever, sorethroat, muscle, cough] that are common amongst all the datasets

In [52]:
directory = "../Data/Symptoms_Demo/Common_Symptoms/"

In [49]:
symptoms = ['fever','cough','muscle','sorethroat','virus']
demo = ['male','female','age 0-4','age 5-15','age 16-44','age 45-64','age 65+']

In [50]:
data_nyumc['virus'] = data_nyumc['flu']
symp_nyumc = data_nyumc[symptoms]
demo_nyumc = data_nyumc[demo]
data_nyumc = pd.concat([symp_nyumc,demo_nyumc],axis = 1)
data_nyumc.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,1,1,0,0,0,1,0,0,1,0,0,0
1,1,1,0,0,0,0,1,0,1,0,0,0
2,1,0,0,0,0,0,1,0,0,0,1,0
3,0,1,0,0,0,0,1,0,0,1,0,0
4,0,1,0,0,0,0,1,0,0,0,0,1

In [53]:
data_nyumc.to_csv(directory+'nyumc.csv',index = False)

In [55]:
#goviral
# data_gv['virus'] = data_gv['flu']
symp_gv = data_gv[symptoms]
demo_gv = data_gv[demo]
data_gv = pd.concat([symp_gv,demo_gv],axis = 1)
data_gv.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,0,0,1,1,1,1.0,0.0,0,0,1,0,0
1,0,0,1,1,1,1.0,0.0,0,0,1,0,0
2,1,1,1,0,1,0.0,1.0,0,0,1,0,0
3,1,1,1,0,1,0.0,1.0,0,0,1,0,0
4,0,1,1,0,1,1.0,0.0,0,0,1,0,0

In [56]:
data_gv.to_csv(directory+'goviral.csv',index=False)

In [ ]:
#fluwatch

In [58]:
data_fw['virus'] = data_fw['flu']
symp_fw = data_fw[symptoms]
demo_fw= data_fw[demo]
data_fw = pd.concat([symp_fw,demo_fw],axis = 1)
data_fw.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,1.0,0.0,0.0,0.0,0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,1.0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,1,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,1.0,1.0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [59]:
data_fw.to_csv(directory+'fluwatch.csv',index=False)

In [61]:
#hongkong

data_hk['virus'] = data_hk['flu']
symp_hk = data_hk[symptoms]
demo_hk= data_hk[demo]
data_hk = pd.concat([symp_hk,demo_hk],axis = 1)
data_hk.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,1.0,1.0,0.0,1.0,1.0,1.0,0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1,0.0,0.0,1.0,0.0,0.0
3,1.0,1.0,1.0,1.0,1.0,0.0,1,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,1.0,0.0,0.0

In [62]:
data_hk.to_csv(directory+'hongkong.csv',index=False)

In [64]:
#hutterite

# data_ht['virus'] = data_hk['flu']
symp_ht = data_ht[symptoms]
demo_ht= data_ht[demo]
data_ht = pd.concat([symp_ht,demo_ht],axis = 1)
data_ht.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0,1,1,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0,0,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0,1,0,1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0,1,0,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0

In [65]:
data_ht.to_csv(directory+'hutterite.csv',index=False)

In [66]:
#loeb
# data_ht['virus'] = data_hk['flu']
symp_lb = data_lb[symptoms]
demo_lb = data_lb[demo]
data_lb = pd.concat([symp_lb,demo_lb],axis = 1)
data_lb.head()

,fever,cough,muscle,sorethroat,virus,male,female,age 0-4,age 5-15,age 16-44,age 45-64,age 65+
0,0,0,0,1,0,0,1,0,0,1,0,0
1,0,1,0,1,1,1,0,0,1,0,0,0
2,0,0,1,1,1,1,0,0,1,0,0,0
3,1,1,0,1,0,1,0,1,0,0,0,0
4,0,0,0,0,1,0,1,0,1,0,0,0

In [67]:
data_lb.to_csv(directory+'loeb.csv',index=False)

In [ ]:
def get_all_features():
    all_features = ['fever','cough','muscle','sorethroat','male','female','age 0-4','age 5-15','age 16-44','age 45-64','age 65+']
#     all_features = list(set(symptoms['NYUMC']) | set(symptoms['GoViral']) | set(symptoms['FluWatch']) | set(symptoms['HongKong']) | set(symptoms['Hutterite']))
#     all_features.append('virus')
    return all_features

In [ ]:
all_features = get_all_features()
print("Features from all the datasets:\n")
for i in all_features:
    print(i)
print("Total number of symptoms across all the datasets :",len(all_features))
print("____________________________________")

In [ ]:
new_symptoms = defaultdict()

In [ ]:
def unify_feature_space(dataset,symptoms,target_variable,all_features):
    dataset = dataset[all_features]
    added_features = []
#     for i in all_features:
#         if i not in symptoms:
#             dataset[i] = 0
#             added_features.append(i)
    if target_variable == 'flu' :
        print("Target variable is Flu")
        dataset.rename(columns = {target_variable:'virus'},inplace = True)
    print("Number of columns now are : ",len(list(dataset.columns)))
    return dataset,added_features

#### Add features for NYUMC

In [ ]:
data_nyumc,added_features_nyumc = unify_feature_space(data_nyumc,symptoms,target_variable['NYUMC'],all_features)
# print("Existing features in NYUMC :\n")
# for i in symptoms['NYUMC']:
#     print(i)
# print("____________________________________")
# print("Added features :\n")
# for i in added_features_nyumc:
#     print(i)
#     new_symptoms['NYUMC'].append(i)
# print("____________________________________")
data_nyumc.head()

#### Add features for GoViral

In [ ]:
new_symptoms['GoViral'] = symptoms['GoViral']
data_gv,added_features_gv = unify_feature_space(data_gv,symptoms['GoViral'],target_variable['GoViral'],all_features)
print("Existing features in GoViral :\n")
for i in symptoms['GoViral']:
    print(i)
print("____________________________________")
print("Added features :\n")
for i in added_features_gv:
    print(i)
    new_symptoms['GoViral'].append(i)
print("____________________________________")
data_gv.head()

#### Add features for FluWatch

In [ ]:
new_symptoms['FluWatch'] = symptoms['FluWatch']
data_fw,added_features_fw = unify_feature_space(data_fw,symptoms['FluWatch'],target_variable['FluWatch'],all_features)
print("Existing features in FluWatch :\n")
for i in symptoms['FluWatch']:
    print(i)
print("____________________________________")
print("Added features :\n")
for i in added_features_fw:
    print(i)
    new_symptoms['FluWatch'].append(i)
print("____________________________________")
print("New Symptoms :\n")
for k,v in new_symptoms.items():
    print(k,v)

#### Add features for HongKong

In [ ]:
new_symptoms['HongKong'] = symptoms['HongKong']
data_hk,added_features_hk = unify_feature_space(data_hk,symptoms['HongKong'],target_variable['HongKong'],all_features)
print("Existing features in HongKong :\n")
for i in symptoms['HongKong']:
    print(i)
print("____________________________________")
print("Added features :\n")
for i in added_features_hk:
    print(i)
    new_symptoms['HongKong'].append(i)
print("____________________________________")
print("New Symptoms :\n")
for k,v in new_symptoms.items():
    print(k,v)

#### Add features for Hutterite

In [ ]:
new_symptoms['Hutterite'] = symptoms['Hutterite']
data_ht,added_features_ht = unify_feature_space(data_ht,symptoms['Hutterite'],target_variable['Hutterite'],all_features)
print("Existing features in Hutterite :\n")
for i in symptoms['Hutterite']:
    print(i)
print("____________________________________")
print("Added features :\n")
for i in added_features_ht:
    print(i)
    new_symptoms['Hutterite'].append(i)
print("____________________________________")
print("New Symptoms :\n")
for k,v in new_symptoms.items():
    print(k,v)

### Ensure that only the requried features are present

In [ ]:
required_features = ['fever',
                     'sorethroat',
                     'cough',
                     'muscle',
                     'headache',
                     'fatigue',
                     'vomit',
                     'nausea',
                     'diarrhea',
                     'chills',
                     'sneeze',
                     'shortness of breath',
                     'phlegm',
                     'blockednose',
                     'earache',
                     'leg pain',
                     'runnynose',
                     'age 0-4',
                     'age 5-15',
                     'age 16-44',
                     'age 45-64',
                     'age 65+',
                     'male',
                     'female',
                     'virus']

In [ ]:
def feature_selection(dataset,required_features = required_features):
    dataset_features = list(dataset.columns)
    #check if we have missed out any symptoms
    not_present = [i for i in required_features if i not in dataset_features]
    print("The features we have missed are : ",not_present)
    excess = [i for i in dataset_features if i not in required_features]
    print("The excess features are : ",excess)
    dataset.drop(excess,axis = 1,inplace = True)
    dataset = dataset[required_features]
    return dataset

In [ ]:
data_nyumc = feature_selection(data_nyumc)

In [ ]:
data_gv = feature_selection(data_gv)

In [ ]:
data_fw = feature_selection(data_fw)

In [ ]:
data_hk = feature_selection(data_hk)

In [ ]:
data_ht = feature_selection(data_ht)

### Save the datasets with same feature space

In [ ]:
def save_file(dataframe_,filename_):
    print("Columns in this dataset are : ",list(dataframe_.columns))
    print(len(list(dataframe_.columns)))
    directory = "../Data/With_Demographics/"
    filename = directory+filename_
    if os.path.isfile(filename):
        print("File exists!")
    else:
        dataframe_.to_csv(filename,index=False)

In [ ]:
save_file(data_nyumc,"nyumc.csv")

In [ ]:
save_file(data_gv,"goviral.csv")

In [ ]:
save_file(data_fw,"fluwatch.csv")

In [ ]:
save_file(data_hk,"hongkong.csv")

In [ ]:
save_file(data_ht,"hutterite.csv")

In [ ]:
data_ht.columns

In [ ]:
data_ht.head()

In [ ]:
data_hk.head()